name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  ci:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: install openresty
      run: |
        wget -qO - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        sudo apt-get -y update --fix-missing
        sudo apt-get -y install software-properties-common
        sudo add-apt-repository -y "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main"
        sudo apt-get update
        sudo apt-get install openresty     

    - uses: leafo/gh-actions-lua@v6
      with:
        luaVersion: "5.1.5"

    - uses: leafo/gh-actions-luarocks@v2
      with:
        luarocksVersion: "2.4.4"

    - name: install luacheck
      run: |
        luarocks install luacheck
        luarocks install busted

    - name: make test
      run: |
        make dev
        make test
