name: unit-test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:

  testing:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: install lua
      run: |
        sudo apt-get update
        sudo apt-get install lua5.1

        wget https://github.com/luarocks/luarocks/archive/v2.4.4.tar.gz
        tar -xf v2.4.4.tar.gz
        cd luarocks-2.4.4
        ./configure --prefix=/usr > build.log 2>&1 || (cat build.log && exit 1)
        make build > build.log 2>&1 || (cat build.log && exit 1)
        sudo make install > build.log 2>&1 || (cat build.log && exit 1)
        cd ..
        rm -rf luarocks-2.4.4

        sudo luarocks install luacheck > build.log 2>&1 || (cat build.log && exit 1)

    - name: make test
      run: |
        make dev
        make test
